name: Deploy blog

on:
  push:
    tags:
      - "deploy-blog-*"
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag_name
        run: ls
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.107.0'
          extended: true
      - name: Build
        run: cd blog && hugo --minify --destination ./public
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'blog/public'
          destination_dir: blog
      # - name: Update deployment status (success)
      #   if: success()
      #   uses: chrnorm/deployment-status@releases/v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     target_url: https://aws-bucket.s3.ap-northeast-2.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html
      #     state: 'success'
      #     deployment_id: ${{ steps.test.outputs.deployment_id }}
